spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: microlabo
          uri: http://localhost:8081
          predicates:
            - Path=/patients/**
          filters:
            - AuthenticationFilter

        - id: microfront
          uri: http://localhost:8082
          predicates:
            - Path=/api/**
          filters:
            - AuthenticationFilter

        - id: micronotes
          uri: http://localhost:8083
          predicates:
            - Path=/notes/**
          filters:
            - AuthenticationFilter

        - id: microrisk
          uri: http://localhost:8084
          predicates:
            - Path=/risk/**
          filters:
            - AuthenticationFilter

        - id: microauth
          uri: http://localhost:8085
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
