spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: microlabo
          uri: http://microlabo:8081
          predicates:
            - Path=/patients/**
#          filters:
#            - AuthenticationFilter

        - id: health-check
          uri: http://microlabo:8081
          predicates:
            - Path=/health

        - id: microfront
          uri: http://microfront:8082
          predicates:
            - Path=/api/**, /v3/api-docs, /swagger-ui/**
          filters:
            - AuthenticationFilter

        - id: static-resources
          uri: http://microfront:8082
          predicates:
            - Path=/webjars/**
          filters:
            - AuthenticationFilter

        - id: micronotes
          uri: http://micronotes:8083
          predicates:
            - Path=/notes/**
          filters:
            - AuthenticationFilter

        - id: microrisk
          uri: http://microrisk:8084
          predicates:
            - Path=/risk/**
          filters:
            - AuthenticationFilter

        - id: microauth
          uri: http://microauth:8085
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client: DEBUG