spring:
  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/uaa/oauth/token

  cloud:
    gateway:
      routes:
        - id: microlabo
          uri: http://localhost:8081
          predicates:
            - Path=/patients/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: microfront
          uri: http://localhost:8082
          predicates:
            - Path=/**
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=Cookie

        - id: micronotes
          uri: http://localhost:8083
          predicates:
            - Path=/notes/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: microrisk
          uri: http://localhost:8084
          predicates:
            - Path=/risk/**
          filters:
            - RemoveRequestHeader=Cookie

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
